version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/node:10.8.0-stretch-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - run: npm run test